### ISSUE TITLE
초대장 수정, 삭제 기능 구현

### ISSUE THREAD

**Issue by khsrla9806** [livable-final/server#57]
### TODO
- [x] 초대장 삭제 기능 구현
- [x] 초대장 삭제 Service 테스트 구현
- [x] 초대장 삭제 POSTMAN 테스트
- [x] 초대장 수정 기능 구현
- [x] 초대장 수정 POSTMAN 테스트
- [x] 초대장 수정 Service 테스트 구현
- [x] 초대장 수정 Controller 테스트 구현 (유효성 검사 확인)

<br>

### 삭제 프로세스
(1) `DELETE` /api/invitation/{invitationId}
(2) 요청 받은 `invitationId`로 초대장을 조회
(3) 초대장이 존재하는지 확인, 요청한 `Member`가 작성한 초대장이 맞는지 확인
(4) 초대장 방문 날짜가 지났는지 확인
  - 이미 지난 날짜의 초대장은 삭제되지 않도록 해야 한다.
  - 주차 등록이나 여러 데이터가 묶여 있기 때문에
  - 애초에 클라이언트는 지난 초대장에 대해서 리스트를 넘겨 받지 않는다.
  
(5) 초대장에 등록된 장소가 예약한 장소(`commonPlace`)라면 해당 초대장에 연결 되어 있는 모든 예약 정보 삭제
(6) 초대장에 등록 되었던 방문자 데이터 + 주차 등록 데이터 모두 삭제

<br>

### 삭제 벌크 연산
```java
@Modifying
@Query("delete from InvitationReservationMap irm where irm.invitation.id = :invitationId")
void deleteAllByInvitationId(Long invitationId);
```
- 내가 작성하는 코드에서는 1차 캐싱에 대한 이슈가 없어서 벌크연산을 사용했다.
- 근데 만약 해당 메서드를 다른 작업자가 재사용한다면 잠재적인 문제를 일으킬 수 있지 않을까?
- 주석으로 표시를 해둬야하지? 어떻게 표시해야할지 고민을 조금 더 해봐야겠다.

<br><hr>

### 수정 프로세스
(1) `PATCH` /api/invitation/{invitationId}
(2) Request 받은 데이터들로 변경 감지를 통한 데이터 수정을 진행
(3) 수정할 수 없는 값 들에 대한 유효성 검사를 진행

<br>

### 수정 기능 고려 사항
(1) 초대목적 (`purpose`)는 수정이 불가하다.
(2) 초대목록 (`visitors`)는 추가만 가능하다. (삭제는 불가능)
  - 추가된 인원에게만 알림톡을 보낸다.
  - 만약 초대장의 시간이 변경된 경우에는 모두에게 알림톡을 다시 보낸다.
  
(3) 예약된 장소를 사용하지 않은 초대장의 초대일시 (`date`, `time`)는 변경이 가능하다.
  - commonPlaceId가 `null`이면 초대일시 변경은 가능하다.
  
(4) 예약된 장소를 사용하고, 목적이 면접이라면 초대일시 변경이 가능하다.
  - commonPlaceId가 null이 아니라면 목적이 면접 때만 변경이 가능하다.
  
(5) 팁 작성(description)은 수정이 가능하다.

<br>

### 수정 기능 중
```java
  if (isModifiedInvitationDateTime(invitation, dto)) {
      shouldSendToAlreadyVisitor = true;
      if (isReservedCommonPlace(dto.getCommonPlaceId())) {
  
          invitationReservationMapRepository.deleteAllByInvitationId(invitation.getId());
          reserveNewCommonPlaces(dto, invitation);
      }
  }
```
- `deleteAllByInvitationId` 벌크 삭제 쿼리를 사용 후
- `reserveNewCommonPlaces` 새로운 예약 내역을 만듬
- 기존 시간과 겹치는 시간을 예약하는 경우도 생각해서 완전히 연관된 예약은 지우고, 새롭게 다시 예약하는게 안전하다고 판단

<br>

### Issue
- DTO안에 있는 다른 DTO의 리스트 Validation 검증?
  ```java
  @Getter
  @Builder
  public static class UpdateDTO {
      private Long commonPlaceId;
      private String description;
  
      @NotNull(message = NOT_NULL)
      @FutureOrPresent(message = REQUIRED_FUTURE_DATE)
      private LocalDateTime startDate;
  
      @NotNull(message = NOT_NULL)
      @FutureOrPresent(message = REQUIRED_FUTURE_DATE)
      private LocalDateTime endDate;
  
      @Valid
      @NotNull(message = NOT_NULL)
      private List<VisitorForUpdateDTO> visitors;
  }
  
  @Getter
  @Builder
  public static class VisitorForUpdateDTO {
      @NotNull(message = NOT_NULL)
      private String name;
  
      @NotNull(message = NOT_NULL)
      private String contact;
  
      public Visitor toEntity(Invitation invitation) {
          return Visitor.builder()
                  .invitation(invitation)
                  .name(name)
                  .contact(contact)
                  .firstVisitedTime(null)
                  .build();
      }
  }
  ```
  - private List<VisitorForUpdateDTO> visitors의 요소 하나하나 Validation 검사를 하기 위해서는 여기에도 @Valid를 붙여줘야 한다.
